// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzmizuhgrpjmlsshcwku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6bWl6dWhncnBqbWxzc2hjd2t1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMTI5NzUsImV4cCI6MjA2Nzc4ODk3NX0.K0HbmeWzNwFY6mABfxLNl0egBvrsjeYz9gXXGUe1p80";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});